### ISSUE TITLE
Feedbacks and suggestions

### ISSUE THREAD

**Issue by abhiprojectz** [abhiprojectz/SingularGPT#1]
Early testers and users, please provide suggestions and feedbacks here, 

i need some maintainer, please reach out to here or to me.

Pinning this straight away.

**Comment by cometbus** [comment]
I can't get this to run 

(venv31) E:\git\Singular>python main.py
{'id': 'cmpl-73WUl3y7otB0KBhbktEUMZoS5R8v8', 'object': 'text_completion', 'created': 1681074251, 'model': 'text-davinci-002', 'choices': [{'text': '\n\n1. Go to amazon.com.\n2. In the search bar, type in "drain cover".\n3. A list of results will appear. Find a drain cover that you like and click on the product page.\n4. On the product page, select the quantity you would like to purchase and click "Add to Cart".\n5. Follow the prompts to complete your purchase.', 'index': 0, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 10, 'completion_tokens': 84, 'total_tokens': 94}}
E:\git\Singular\instructions_lib
[Automation script has been generated.]
data/input/curr_img.png
[ WARN:0@0.784] global loadsave.cpp:244 cv::findDecoder imread_('C:\\Users\\abhis\\Desktop\\tx_5.PNG'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "E:\git\Singular\script.py", line 5, in <module>
    zex.image(r"C:\\Users\\abhis\\Desktop\\tx_5.PNG").click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\git\Singular\zexui_lib\zexui.py", line 229, in image
    _x = find_location_of_img_obj(self.img_path, target_img)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\git\Singular\zexui_lib\base_functions.py", line 100, in find_location_of_img_obj
    cropped_gray = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2GRAY)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


(venv31) E:\git\Singular>
